name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESSKEY }}
    - name: Build the Docker image
      run:  docker build . --file Dockerfile --tag somu9491/testing:latest
    - name: push to dockerhub
      run: docker push somu9491/testing:latest
