name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name : checkout-code
      uses: actions/checkout@v3
    - name: login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_HUB_ACCESSKEY }}
    - name: Build and push the Docker image
      uses: docker/build-push-action@v1
      with:
        context: .
        push: true
        tags: somu9491/gitimage:latest, somu9491/gitimage:$(date +%s)
      
