name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESSKEY }}
      run: 
        docker login -u somu9491 -p $DOCKER_HUB_ACCESSKEY
    - name: Build the Docker image
      run: |
        registry: dockerhub.com
        docker build . --file Dockerfile --tag somu9491/testing:latest
    - name: push to dockerhub
      run: docker push somu9491/testing:latest
